<a href="https://colab.research.google.com/github/MansiSinghP/MACHINE-LEARNING-PROJECTS/blob/main/MNIST_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#loading the dataset
dataset=pd.read_csv('https://raw.githubusercontent.com/cerndb/dist-keras/master/examples/data/mnist.csv')
dataset.head()

label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0      1       0       0       0  ...         0         0         0         0
1      0       0       0       0  ...         0         0         0         0
2      1       0       0       0  ...         0         0         0         0
3      4       0       0       0  ...         0         0         0         0
4      0       0       0       0  ...         0         0         0         0

[5 rows x 785 columns]

In [3]:
dataset.shape

(42000, 785)

In [4]:
#dropping columns
dataset.drop(dataset.iloc[:, 3:786], inplace=True, axis=1)

In [5]:
dataset.shape

(42000, 3)

In [6]:
dataset.head()

label  pixel0  pixel1
0      1       0       0
1      0       0       0
2      1       0       0
3      4       0       0
4      0       0       0

1.SVM classifier

Linear SVM classifier

In [7]:
X = dataset.drop('label', axis=1)
y = dataset['label']

In [8]:
#splitting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [ ]:
#Training the algorithm
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
#making predictions
y_pred = svclassifier.predict(X_test)

In [ ]:
#Evaluating the algorithm
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[  0 846   0   0   0   0   0   0   0   0]
 [  0 963   0   0   0   0   0   0   0   0]
 [  0 866   0   0   0   0   0   0   0   0]
 [  0 840   0   0   0   0   0   0   0   0]
 [  0 811   0   0   0   0   0   0   0   0]
 [  0 754   0   0   0   0   0   0   0   0]
 [  0 821   0   0   0   0   0   0   0   0]
 [  0 837   0   0   0   0   0   0   0   0]
 [  0 851   0   0   0   0   0   0   0   0]
 [  0 811   0   0   0   0   0   0   0   0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       846
           1       0.11      1.00      0.21       963
           2       0.00      0.00      0.00       866
           3       0.00      0.00      0.00       840
           4       0.00      0.00      0.00       811
           5       0.00      0.00      0.00       754
           6       0.00      0.00      0.00       821
           7       0.00      0.00      0.00       837
           8       0.00      0.00      0.00       851
           9       0.00     

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Polynomial Kernel SVM classifier

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=8, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

Making Predictions

In [ ]:
y_pred = svclassifier.predict(X_test)

Evaluating the algorithm

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[  0 846   0   0   0   0   0   0   0   0]
 [  0 963   0   0   0   0   0   0   0   0]
 [  0 866   0   0   0   0   0   0   0   0]
 [  0 840   0   0   0   0   0   0   0   0]
 [  0 811   0   0   0   0   0   0   0   0]
 [  0 754   0   0   0   0   0   0   0   0]
 [  0 821   0   0   0   0   0   0   0   0]
 [  0 837   0   0   0   0   0   0   0   0]
 [  0 851   0   0   0   0   0   0   0   0]
 [  0 811   0   0   0   0   0   0   0   0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       846
           1       0.11      1.00      0.21       963
           2       0.00      0.00      0.00       866
           3       0.00      0.00      0.00       840
           4       0.00      0.00      0.00       811
           5       0.00      0.00      0.00       754
           6       0.00      0.00      0.00       821
           7       0.00      0.00      0.00       837
           8       0.00      0.00      0.00       851
           9       0.00     

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Random Forest

In [18]:
#training the algorithm
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=20, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [21]:
#Evaluating the algorithm
# Check accuracy score 
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))


[[  0 800   0   0   0   0   0   0   0   0]
 [  0 965   0   0   0   0   0   0   0   0]
 [  0 814   0   0   0   0   0   0   0   0]
 [  0 913   0   0   0   0   0   0   0   0]
 [  0 802   0   0   0   0   0   0   0   0]
 [  0 792   0   0   0   0   0   0   0   0]
 [  0 824   0   0   0   0   0   0   0   0]
 [  0 869   0   0   0   0   0   0   0   0]
 [  0 781   0   0   0   0   0   0   0   0]
 [  0 840   0   0   0   0   0   0   0   0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       800
           1       0.11      1.00      0.21       965
           2       0.00      0.00      0.00       814
           3       0.00      0.00      0.00       913
           4       0.00      0.00      0.00       802
           5       0.00      0.00      0.00       792
           6       0.00      0.00      0.00       824
           7       0.00      0.00      0.00       869
           8       0.00      0.00      0.00       781
           9       0.00     

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


3. 1-vs-rest classifier

In [25]:
#SVC Model
model = SVC(gamma='scale',random_state=0)
#Define 1-vs-Rest Strategy / Classifier
ovr = OneVsRestClassifier(model)

#fit model to training data
ovr.fit(X_train, y_train)

#Predications
ovr_pred = ovr.predict(X_test)

#Adding Predictions to Test Dataset
ovr_df = X_test.copy()
ovr_df.insert(2,"Actual",y_test, True)
ovr_df.insert(3,"Predicted",ovr_pred, True)
#Inspect
ovr_df.head()

pixel0  pixel1  Actual  Predicted
8982        0       0       6          9
21222       0       0       7          9
24775       0       0       9          9
19518       0       0       1          9
16916       0       0       1          9